### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by Austyns** [clearspark/django-monthfield#6]
Nice concept. But please, How do i integrate into project? Thanks

**Comment by clearspark** [comment]
Hi,
I am not in a position to reply at length right now but the basic idea is to use it in your models.py

```
...
from month.models import MonthField

class MyModel(models.Model)
    billing_month = MonthField()
    other_field1 = ...
    other_field2 = ...
```

**Comment by Austyns** [comment]
Thanks @clearspark. Pretty straight forward
