### ISSUE TITLE
Add module to PyPi

### ISSUE THREAD

**Issue by devedetti** [clearspark/django-monthfield#7]
Please, upload this module to https://pypi.python.org/pypi

Thanks for your time :)

**Comment by matthysk** [comment]
Hi,
That's a good idea. Thank you. I haven't done it before so I just need to read the instructions first. Please be patient :)

**Comment by clearspark** [comment]
Uploaded to pypi!

https://pypi.python.org/pypi/django-monthfield

Doesn't show up with pip search yet.

**Comment by devedetti** [comment]
:) Thanks!
